name: qrscanner
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  barcode_scan: ^1.0.0
  cupertino_icons: ^0.1.2
  fluttertoast: ^3.1.0
  url_launcher: ^5.4.0

  time: ^1.3.0
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true